### ISSUE TITLE
Render image in statusline

### ISSUE THREAD

**Issue by aloussase** [3rd/image.nvim#17]
Hi! Awesome plugin. Do you think there is a way to use this to render images on the statusline?
I've been looking for a way to have something like emacs's nyan-mode in neovim for a while now
and this plugin gives me hope.

**Comment by 3rd** [comment]
Hey, glad you like it! It's definitely possible, do you use Kitty?

**Comment by aloussase** [comment]
Great to hear! Yes, I use Kitty.

**Comment by 3rd** [comment]
@aloussase
It would have some issues with tmux and interacting with other panes, as the cursor handling gets messed up somehow, probably because "move cursor" commands from inactive panes are ignored, as they should be.

A workaround would be to disable all rendering when Neovim looses focus, I'll look into that.

Did a small test that's super unoptimized and it's not that... bad, I guess.


https://github.com/3rd/image.nvim/assets/59587503/76a3a5cb-fe41-47c4-a076-4d25bfa32e0a

**Comment by aloussase** [comment]
I see what you mean. Thanks for taking the time to work on this! I'll be attentive to updates.

**Comment by 3rd** [comment]
No dice with Tmux (https://github.com/tmux/tmux/issues/3325), could only work with animations, not manual frame-by-frame stuff.

**Comment by 3rd** [comment]
I'll close this issue as it requires implementing Kitty's animation protocol, and it's out of scope for now. Will focus on reworking the plugin from the PoC state to something stable and fast, and with a nice API.

** But would be super happy to add animations if anyone wants to look into that, we **do want animations** at some point, and I think ueberzug already supports GIFs / WebM.
